PROJECT STRUCTURE
Amedzro-Elikplim/Minimalist pull request #2
Opened 2022-02-26 13:39 UTC by Amedzro-Elikplim

# MINIMALIST APP 

- Display to do in index.html
- Bundle javascript using webpack
- Style todo list using flex layout
- Implement modular architecture
- Dynamically iterate over todo array and display each todo list 
- Add input field to accept todo from user

2022-02-26 14:09 UTC, brytebee requested changes
Hi, @Amedzro-Elikplim 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- good documentation✔️
- webpack properly setup✔️
- no linters✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 14:09 UTC, brytebee commented on src/index.js
> +];
- [ ] **Required:** You have done an amazing job so far. However, your list should be loaded in the order of index.

**Hint:** `Array.sort((a, b) => a.index - b.index);`

2022-02-26 14:33 UTC, ShoiraTa commented
## **STATUS: APPROVED  🟢 ** 
------
### Hi @Amedzro-Elikplim , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 14:34 UTC, merged

2022-04-26 10:24 UTC, emmanuellekamwa reviewed
**STATUS: REQUIRED CHANGES ✔🍾🎉**
Hello @Amedzro-Elikplim 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- You asked for the changes in a polite and friendly way.
- You documented your work professionally.✔
- Github inline comments feature is used properly.

## Required Changes ♻️
- Since you are repeating the module instead of submitting the old pull request you have to create a new pull request with a new change so that it can be reviewed.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 10:57 UTC, Amedzro-Elikplim commented
Am just doing as told by student success. I already have my project approved and there is no change to make. Why do I need to make a change? In addition, I submitted an old pull request yesterday and it was approved without any problem. Can you please explain your suggestions in detail?

2022-04-26 11:01 UTC, emmanuellekamwa commented
You just need to make a small change like adding something to your readme
file and then committing that change. Even I had this type of issue and I
was told to submit a new pull request with a new change so that I can get
my project approved.

Le mar. 26 avr. 2022 à 11:57, Eli ***@***.***> a écrit :

> Am just doing as told by student success. I already have my project
> approved and there is no change to make. Why do I need to make a change? In
> addition, I submitted an old pull request yesterday and it was approved
> without any problem. Can you please explain your suggestions in detail?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Amedzro-Elikplim/Minimalist/pull/2#issuecomment-1109652754>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOTSG72VH4B3HV3XKM4LQOTVG7D2HANCNFSM5PM7IDFA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>